### ISSUE TITLE
Prepare hero image files

### ISSUE THREAD

**Issue by belauzas** [front-end-by-rimantas/19-grupe-coming-soon#2]
- hero logo (png)
- hero background (jpg)

Resource: https://cdn.discordapp.com/attachments/648536139677958156/651479019476221953/coming-soon-wide.png

**Comment by Vaidmine** [comment]
pagaliau radau kur parašyti, kad aš darau :) 
prašome priskirti

**Comment by belauzas** [comment]
Green light ✅
